### ISSUE TITLE
Verify `mas` on MacOS Mojave

### ISSUE THREAD

**Issue by philoserf** [philoserf/newcastle#37]
I know `mas` didn't work on the early betas of MacOS Mojave's with some App Store updates.

Before it goes to release, figure it out and fix it. Contribute upstream if required and appropriate

ref: https://github.com/mas-cli/mas/issues/164. 
prior art: #6 and #9

**Comment by phatblat** [comment]
mas 1.4.3 fixes some issues on Mojave although the signin command is disabled
